### ISSUE TITLE
Put a link to dataverse.org on the About page

### ISSUE THREAD

**Issue by mengland80** [gdcc/www.gdcc.io#10]
I arrived at gdcc.io via search results and could only tell the GDCC 'dataverse' was a reference to the same dataverse as dataverse.org by looking at the names of the people attached to both. Just throw a link to dataverse.org on the about page or somewhere else up front to make it clear.

**Comment by pdurbin** [comment]
@mengland80 welcome! Great idea! I just made a pull request:

- #11

What do you think? Is that enough links?
