### ISSUE TITLE
last news post was November 2023

### ISSUE THREAD

**Issue by pdurbin** [gdcc/www.gdcc.io#12]
Should we update https://www.gdcc.io/news.html ?

At the very least, we could link to the YouTube video from the 2024 Community Meeting, the GDCC update session.

**Comment by philippconzett** [comment]
Sorry for my late reply!
Yes, I agree, we should! I've added a post about the GDCC updates at DCM24.
I suggest we (you! :-) ) also add a link each month to the community updates.

**Comment by pdurbin** [comment]
@philippconzett thanks! Looks fantastic! I'd say we can go ahead and close this issue.

Based on those links I added an entry to DataverseTV: https://github.com/IQSS/dataverse-tv

![Screenshot 2024-10-15 at 2 36 07 PM](https://github.com/user-attachments/assets/f3d370c2-51e5-457e-bc40-53bacd0842ab)

As for the Dataverse Community News, I'm honored but I'm not particularly interested in the extra work of posting it in two places. Maybe we could find a place to link to https://groups.google.com/g/dataverse-community?label=community_news at least, which is the collection of all the news posts. 🤔 Maybe we could have a new issue for this. Not sure.

![Screenshot 2024-10-15 at 2 39 41 PM](https://github.com/user-attachments/assets/c290de0d-d124-4460-9461-baa51f663006)

**Comment by philippconzett** [comment]
Thanks, @pdurbin! I can try to post a reference to your news item in the Dataverse Google Group, starting from next month. :-)  Let's close this issue.

**Comment by pdurbin** [comment]
@DieuwertjeBloemen made a huge update in 15b0cb0! 🎉
